tar cjvf b_g_TO_Wminus_t_0Loop_amplitudes.tar.bz2      b_g_TO_Wminus_t_0Loop_amplitudes
tar cjvf b_g_TO_Wminus_t_0Loop_visuals.tar.bz2         b_g_TO_Wminus_t_0Loop_visuals
tar cjvf b_g_TO_Wminus_t_1Loop_amplitudes.tar.bz2      b_g_TO_Wminus_t_1Loop_amplitudes
tar cjvf b_g_TO_Wminus_t_1Loop_visuals.tar.bz2         b_g_TO_Wminus_t_1Loop_visuals
tar cjvf b_g_TO_Wminus_t_2Loop_amplitudes.tar.bz2      b_g_TO_Wminus_t_2Loop_amplitudes
tar cjvf b_g_TO_Wminus_t_2Loop_visuals.tar.bz2         b_g_TO_Wminus_t_2Loop_visuals
tar cjvf dbar_u_TO_Wplus_0Loop_amplitudes.tar.bz2      dbar_u_TO_Wplus_0Loop_amplitudes
tar cjvf dbar_u_TO_Wplus_0Loop_visuals.tar.bz2         dbar_u_TO_Wplus_0Loop_visuals
tar cjvf dbar_u_TO_Wplus_1Loop_amplitudes.tar.bz2      dbar_u_TO_Wplus_1Loop_amplitudes
tar cjvf dbar_u_TO_Wplus_1Loop_visuals.tar.bz2         dbar_u_TO_Wplus_1Loop_visuals
tar cjvf dbar_u_TO_Wplus_2Loop_amplitudes.tar.bz2      dbar_u_TO_Wplus_2Loop_amplitudes
tar cjvf dbar_u_TO_Wplus_2Loop_visuals.tar.bz2         dbar_u_TO_Wplus_2Loop_visuals
tar cjvf eminus_eplus_TO_H_Z_0Loop_amplitudes.tar.bz2  eminus_eplus_TO_H_Z_0Loop_amplitudes
tar cjvf eminus_eplus_TO_H_Z_0Loop_visuals.tar.bz2     eminus_eplus_TO_H_Z_0Loop_visuals
tar cjvf eminus_eplus_TO_H_Z_1Loop_amplitudes.tar.bz2  eminus_eplus_TO_H_Z_1Loop_amplitudes
tar cjvf eminus_eplus_TO_H_Z_1Loop_visuals.tar.bz2     eminus_eplus_TO_H_Z_1Loop_visuals
tar cjvf g_g_TO_t_tbar_0Loop_amplitudes.tar.bz2        g_g_TO_t_tbar_0Loop_amplitudes
tar cjvf g_g_TO_t_tbar_0Loop_visuals.tar.bz2           g_g_TO_t_tbar_0Loop_visuals
tar cjvf g_g_TO_t_tbar_1Loop_amplitudes.tar.bz2        g_g_TO_t_tbar_1Loop_amplitudes
tar cjvf g_g_TO_t_tbar_1Loop_visuals.tar.bz2           g_g_TO_t_tbar_1Loop_visuals
tar cjvf t_TO_Wplus_b_3Loop_amplitudes.tar.bz2         t_TO_Wplus_b_3Loop_amplitudes
tar cjvf t_TO_Wplus_b_3Loop_visuals.tar.bz2            t_TO_Wplus_b_3Loop_visuals
tar cjvf Wplus_t_TO_Wplus_t_3Loop_amplitudes.tar.bz2   Wplus_t_TO_Wplus_t_3Loop_amplitudes
tar cjvf Wplus_t_TO_Wplus_t_3Loop_visuals.tar.bz2      Wplus_t_TO_Wplus_t_3Loop_visuals   
